import json
import re
import uuid
import httpx
import pdfplumber
import logging
import asyncio
from datetime import datetime
from pathlib import Path
from fastapi import FastAPI, File, UploadFile, Request, Query
from fastapi.responses import HTMLResponse, StreamingResponse, JSONResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
import io
from src.json_repair import repair_and_parse, enforce_source_spans
from src.field_spec import load_fields, fields_by_tender_key, fields_by_field_name
from src.prompt_markers import strip_null_rule

# ── New structured matching engine (AP-I1) ────────────────────────────────────
from src.data_loader import load_suppliers
from src.matching import match_suppliers_new, TenderRequirements, Matcher
from src.context_builder import product_type_keyword_fallback, build_system_context, PRODUCT_TYPE_KEYWORDS
from src.tender_store import init_db, build_tender_run, persist_tender_run, read_run_criteria
_SUPPLIERS = load_suppliers()
log_setup = logging.getLogger("haystacked")
log_setup.info("SQLite DB loaded: %d active supplier records", len(_SUPPLIERS))

# ── Logging ───────────────────────────────────────────────────────────────────
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(message)s",
    handlers=[
        logging.StreamHandler(),
        logging.FileHandler("haystacked.log", encoding="utf-8"),
    ],
)
logging.getLogger("multipart").setLevel(logging.WARNING)
logging.getLogger("pdfminer").setLevel(logging.WARNING)
log = logging.getLogger("haystacked")
log.setLevel(logging.DEBUG)

# ── App ───────────────────────────────────────────────────────────────────────
app = FastAPI(title="haystacked – Ausschreibungsanalyse")
app.mount("/static", StaticFiles(directory="static"), name="static")
templates = Jinja2Templates(directory="templates")

OLLAMA_URL      = "http://localhost:11434/api/generate"
OLLAMA_MODEL    = "qwen2.5:7b"
_OLLAMA_NUM_CTX = 32_768  # must match num_ctx in call_ollama() options

# ── In-memory analysis cache — analysis_id → result dict ─────────────────────
_analyses: dict[str, dict] = {}
# ── Config loading — startup checksum auto-regenerates if AP0 xlsx changed ────
_CONFIG_DIR = Path(__file__).parent / "config"
_AP0_PATH      = Path(__file__).parent / "Spec" / "haystacked_AP0_field_spec_v0_10.xlsx"
_PLATFORM_PATH = Path(__file__).parent / "Spec" / "haystacked_platform_config.xlsx"

def _check_and_regen():
    """Auto-regenerate all config files if AP0 xlsx or platform_config xlsx has changed (checksum mismatch)."""
    import hashlib, importlib.util
    checksum_file = _CONFIG_DIR / "ap0_checksum.txt"
    if not _AP0_PATH.exists():
        return
    _platform_bytes = _PLATFORM_PATH.read_bytes() if _PLATFORM_PATH.exists() else b""
    current = hashlib.md5(_AP0_PATH.read_bytes() + _platform_bytes).hexdigest()
    stored  = checksum_file.read_text().strip() if checksum_file.exists() else ""
    if current == stored:
        return
    log.info("AP0 xlsx changed (checksum mismatch) — regenerating config files…")
    spec = importlib.util.spec_from_file_location(
        "generate_all", Path(__file__).parent / "scripts" / "generate_all.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    exit_code = mod.generate(_AP0_PATH, _CONFIG_DIR.parent / "data" / "haystacked.db")
    if exit_code == 0:
        log.info("Config regenerated from AP0 v0.10")
    else:
        log.warning("Config regenerated with warnings — check consistency")

_check_and_regen()
init_db()

# ── Vehicle types — loaded from generated config (no hardcoding) ──────────────
_vehicle_cfg    = json.loads((_CONFIG_DIR / "vehicle_types.json").read_text())
_SIGNED_UNITS = frozenset(
    json.loads((_CONFIG_DIR / "unit_semantics.json").read_text()).get("signed_units", [])
)

# ── Extension column list — loaded once at startup from AP0-generated schema ──
_schema_path = _CONFIG_DIR / "sqlite_schema.json"
_EXT_COLUMNS: list[str] = (
    json.loads(_schema_path.read_text()).get("extensions_columns", [])
    if _schema_path.exists() else []
)

# ── AP0 field index — loaded once from fields.json (generated by generate_all.py) ──
_FIELDS_BY_TENDER_KEY = fields_by_tender_key()  # tender_key → list[FieldSpec]
_FIELDS_BY_FIELD_NAME = fields_by_field_name()  # field_name → list[FieldSpec]

# ── tender_key → uuid translation map — built once at startup ────────────────
# Broadcast to all UUIDs that share a tender_key (multi-sheet fields like min_aisle_width_mm).
from collections import defaultdict as _defaultdict
_TK_TO_UUIDS: dict = _defaultdict(list)
for _spec in load_fields().values():
    if _spec.tender_key and _spec.uuid:
        _TK_TO_UUIDS[_spec.tender_key].append(_spec.uuid)

def _criteria_to_uuid_keyed(criteria: dict) -> dict:
    """Translate tender_key → uuid at the AP0 boundary.
    Non-AP0 keys (detected_domain, summary, etc.) pass through unchanged.
    Multi-sheet fields (e.g. min_aisle_width_mm) are broadcast to all matching UUIDs."""
    result = {}
    for k, v in criteria.items():
        uuids = _TK_TO_UUIDS.get(k)
        if uuids:
            for uid in uuids:
                result[uid] = v
        else:
            result[k] = v
    return result

# ── AP0 allowed-values index — built once at startup from fields.json ───────
# Maps tender_key → (allowed_values_set, field_label) for every Dropdown/Multi-Select
# field that has an allowed_values list.  Used by the generalised LLM retry loop.
# Fields in _AP0_SKIP_VALIDATION are handled by downstream normalisation in app.py
# and must not be double-checked here.
_AP0_SKIP_VALIDATION: frozenset = frozenset()
_AP0_CONSTRAINED_FIELDS: dict = {}   # tender_key → {"allowed": set, "allowed_list": list}
# Startup assertion: all multi-VT specs for the same tender_key must agree on allowed_values.
for _tk, _specs in _FIELDS_BY_TENDER_KEY.items():
    _avs = [tuple(_s.allowed_values or []) for _s in _specs]
    assert len(set(_avs)) <= 1, (
        f"fields.json: tender_key {_tk!r} has inconsistent allowed_values across sheets — "
        "check generate_all.py output."
    )
    if _tk in _AP0_SKIP_VALIDATION:
        continue
    _av = _specs[0].allowed_values
    if _av:
        _AP0_CONSTRAINED_FIELDS[_tk] = {
            "allowed":      {v.lower() for v in _av},
            "allowed_list": _av,
        }
for _sk in _AP0_SKIP_VALIDATION:
    assert _sk not in _AP0_CONSTRAINED_FIELDS, (
        f"{_sk} is in _AP0_SKIP_VALIDATION but AP0 now defines allowed_values for it — "
        f"review the downstream coercion logic and remove from skip list."
    )

# ── Numeric KO fields requiring source-span citation ─────────────────────────
# Built from fields.json — any Float/Integer field with KO_IF_LT or KO_IF_GT.
# The extraction template emits a companion <key>_source for each of these.
# If the companion is absent or null, the value is nulled (inference hallucination guard).
_NUMERIC_KO_TENDER_KEYS: frozenset = frozenset(
    tk for tk, specs in _FIELDS_BY_TENDER_KEY.items()
    if specs[0].operator in ("KO_IF_LT", "KO_IF_GT")
    and specs[0].data_type in ("Float", "Integer")
)

# ── Pass 4c: per-field extraction hints — built from fields.json ──────────────
# Maps tender_key → {hint, sheet} for numeric KO fields — used in Pass 4c to
# build one focused LLM prompt per field instead of a single 40-field batch.
# First-spec-wins for multi-VT fields (e.g. required_min_aisle_width_mm picks Forklift AGV
# sheet); Pass 4c runtime filter then suppresses it for non-Forklift tenders.
_NUMERIC_KO_FIELD_HINTS: dict = {}
for _tk in _NUMERIC_KO_TENDER_KEYS:
    for _spec in _FIELDS_BY_TENDER_KEY.get(_tk, []):
        if _spec.hint and _spec.scope:
            _NUMERIC_KO_FIELD_HINTS[_tk] = {"hint": _spec.hint, "scope": _spec.scope}
            break
assert _NUMERIC_KO_FIELD_HINTS, (
    "fields.json has no numeric KO field hints — run generate_all.py"
)

# ── Layer-2 rescue: per-field unit strings — built from fields.json ──────────
# Maps tender_key → unit string — used only by enforce_source_spans()'s Layer 2
# rescue check (D0 fix). Requires _spec.unit truthy (not just hint/scope) — a
# tender_key shared across scopes (e.g. required_min_aisle_width_mm under both
# Forklift and Tugger) must not let an empty-unit scope entry shadow a real unit
# populated under a different scope for the same key.
_NUMERIC_KO_FIELD_UNITS: dict = {}
for _tk in _NUMERIC_KO_TENDER_KEYS:
    for _spec in _FIELDS_BY_TENDER_KEY.get(_tk, []):
        if _spec.hint and _spec.scope and _spec.unit:
            _NUMERIC_KO_FIELD_UNITS[_tk] = _spec.unit
            break
assert _NUMERIC_KO_FIELD_UNITS, (
    "fields.json has no numeric KO field units — run generate_all.py"
)
for _tk in _NUMERIC_KO_TENDER_KEYS:
    assert _tk in _NUMERIC_KO_FIELD_UNITS and _NUMERIC_KO_FIELD_UNITS[_tk], (
        f"Numeric KO field {_tk!r} has no unit in fields.json — "
        f"L2 rescue will never fire for it. Populate the AP0 Unit column."
    )

# Operator-driven extraction direction for Pass 4c prompts — derived from fields.json.
# KO_IF_LT means the supplier must meet or exceed the tender's threshold → extract MAXIMUM.
# KO_IF_GT means the supplier must not exceed the tender's limit → extract MINIMUM.
_4C_EXTRACTION_DIRECTION: dict = {}
for _tk, _specs in _FIELDS_BY_TENDER_KEY.items():
    _op = _specs[0].operator
    if _op == "KO_IF_LT":
        _4C_EXTRACTION_DIRECTION[_tk] = (
            "If multiple values are present, extract the MAXIMUM — "
            "the supplier must meet or exceed this threshold."
        )
    elif _op == "KO_IF_GT":
        _4C_EXTRACTION_DIRECTION[_tk] = (
            "If multiple values are present, extract the MINIMUM — "
            "the supplier must not exceed this constraint."
        )

assert _NUMERIC_KO_TENDER_KEYS, (
    "fields.json has no KO_IF_LT/KO_IF_GT Float/Integer fields — "
    "source-span enforcement is inactive. Run generate_all.py."
)
assert _4C_EXTRACTION_DIRECTION, (
    "fields.json has no KO_IF_LT/KO_IF_GT fields — "
    "Pass 4c has no extraction direction. Run generate_all.py."
)


def _find_invalid_ap0_fields(criteria: dict, skip: frozenset = frozenset()) -> dict:
    """Return {tender_key: (raw_value, allowed_list)} for every non-null field whose
    value is not found in the AP0 allowed_values list.  Case-insensitive substring
    match mirrors the logic in validate_tender_values().  Multi-value fields (pipe or
    comma separated) are checked element-by-element; only invalid elements are reported.
    Fields in `skip` are excluded (used in Pass 4b to skip fields already validated in 4a)."""
    violations: dict = {}
    for tk, meta in _AP0_CONSTRAINED_FIELDS.items():
        if tk in skip:
            continue
        val = criteria.get(tk)
        if val is None:
            continue
        parts = [p.strip() for p in str(val).replace("|", ",").split(",") if p.strip()]
        allowed_lower = meta["allowed"]
        invalid_parts = [
            p for p in parts
            if not any(p.lower() in al or al in p.lower() for al in allowed_lower)
        ]
        if invalid_parts:
            violations[tk] = (", ".join(invalid_parts), meta["allowed_list"])
    return violations


def _build_correction_prompt(violations: dict, original_text: str) -> str:
    """Build a targeted correction user-prompt from AP0 violation data.
    No field names or allowed values are hardcoded — everything comes from
    the violations dict which is derived from _FIELDS_BY_TENDER_KEY (fields.json SSoT)."""
    lines = [
        "The previous extraction returned invalid values for the following fields.",
        "For each field, the invalid value and the complete list of allowed AP0 values are shown.",
        "Re-extract ONLY these fields from the document and return a JSON object containing",
        "only the corrected keys.  Use null if the document does not specify the field.",
        "Do not return any other keys.",
        "",
    ]
    for tk, (bad_val, allowed_list) in violations.items():
        lines.append(f"Field: {tk}")
        lines.append(f"  Invalid value extracted: {bad_val!r}")
        lines.append(f"  Allowed values: {', '.join(repr(a) for a in allowed_list)}")
        lines.append("")
    lines += [
        "DOCUMENT (excerpt — first 4000 chars):",
        original_text[:4000],
    ]
    return "\n".join(lines)
_VT_OVERRIDES   = _vehicle_cfg.get("text_overrides", [])      # [{regex, canonical}]

_FIELD_TEXT_FALLBACKS = _vehicle_cfg.get("field_text_fallbacks", [])  # [{tender_key, regex, value, only_if_null}]
_scope_reg        = json.loads((_CONFIG_DIR / "scope_registry.json").read_text())
_LEGACY_MAP       = _scope_reg.get("legacy_map", {})
_RESOLUTION_ORDER = _scope_reg.get("resolution_order", {})
_shared_candidates = [
    data["scope_id"] for data in _scope_reg["scopes"].values() if data.get("parent") == "*"
]
assert len(_shared_candidates) >= 1, (
    f"scope_registry.json: expected at least 1 child of '*', found {_shared_candidates}. "
    "Add domain-level scopes to scope_registry to enable multi-domain support."
)
_EXTRACTABLE_DOMAINS = frozenset(_shared_candidates)
assert _EXTRACTABLE_DOMAINS, "scope_registry.json: no scopes with parent='*' found — run generate_all.py"
assert _LEGACY_MAP, "scope_registry.json missing legacy_map — run generate_all.py"
assert set(_LEGACY_MAP.values()) <= set(_RESOLUTION_ORDER), (
    f"leaf scopes without resolution_order entry: {set(_LEGACY_MAP.values()) - set(_RESOLUTION_ORDER)}"
)
_VT_MAP_CFG     = _scope_reg.get("variant_map", {})           # variant_lower → canonical (Step 7)
_AGV_DETECT_KWS = _scope_reg.get("agv_detection_keywords", [])  # domain detection fallback keywords (Step 7)
_VALID_VTS = {                                                 # canonical types with scoring bucket (Step 7)
    node["canonical_name"]
    for node in _scope_reg["scopes"].values()
    if node.get("scoring_bucket")
}
assert set(_VT_MAP_CFG.values()) <= set(_LEGACY_MAP), (
    f"variant_map values without legacy_map entry: {set(_VT_MAP_CFG.values()) - set(_LEGACY_MAP)}"
)
_DOMAIN_KWS: dict = _scope_reg.get("domain_keywords", {})
# Domain-scoped valid Pass 4a output values (derived, not hardcoded).
# Only multi-leaf domains need Pass 4a classification: valid outputs = canonical_names
# of child leaves. Single-leaf domains skip Pass 4a entirely (OI-107) — their sole
# canonical_name is deterministic, so they never enter this dict.
_DOMAIN_CLASSIF_VALUES: dict = {}
_single_leaf_domains: set = set()
for _dom in _EXTRACTABLE_DOMAINS:
    _children = [
        n["canonical_name"]
        for n in _scope_reg["scopes"].values()
        if n.get("parent") == _dom and n.get("canonical_name")
    ]
    if _children:
        _DOMAIN_CLASSIF_VALUES[_dom] = frozenset(_children)
    else:
        _single_leaf_domains.add(_dom)
_SINGLE_LEAF_DOMAINS = frozenset(_single_leaf_domains)
assert all(_DOMAIN_CLASSIF_VALUES.values()), (
    f"_DOMAIN_CLASSIF_VALUES has empty entry — check scope_registry.json: {_DOMAIN_CLASSIF_VALUES}"
)
assert _SINGLE_LEAF_DOMAINS | set(_DOMAIN_CLASSIF_VALUES) == _EXTRACTABLE_DOMAINS
assert all(
    _scope_reg["scopes"][_d].get("canonical_name") for _d in _SINGLE_LEAF_DOMAINS
), f"single-leaf domain missing canonical_name in scope_registry.json: {_SINGLE_LEAF_DOMAINS}"
# Phase 3 TODO: replace break-on-first with score-based selection

# ── NACE — loaded from generated config ───────────────────────────────────────
_nace_cfg     = json.loads((_CONFIG_DIR / "nace_codes.json").read_text())
CATEGORY_LIST = "\n".join(_nace_cfg.get("codes", []))
log.info("NACE codes loaded: %d Prio-1 entries", len(_nace_cfg.get("codes", [])))

# ── OI-98: contact-fallback field sets — derived from Basic Extraction Schema's
# "Contact Fallback" column (platform_config.xlsx → config/nace_codes.json).
# TRIGGER decides whether the fallback pass runs; TARGET is the full set of
# fields it may fill in (trigger fields are always also targets).
_CONTACT_FALLBACK_TRIGGER: frozenset = frozenset(
    e["key"] for e in _nace_cfg.get("basic_schema", []) if e.get("contact_fallback") == "trigger"
)
_CONTACT_FALLBACK_TARGET: frozenset = frozenset(
    e["key"] for e in _nace_cfg.get("basic_schema", [])
    if e.get("contact_fallback") in ("trigger", "target")
)
assert _CONTACT_FALLBACK_TRIGGER, (
    "no basic_schema field has contact_fallback='trigger' — check platform_config.xlsx"
)
assert _CONTACT_FALLBACK_TRIGGER <= _CONTACT_FALLBACK_TARGET

# ── Prompts ───────────────────────────────────────────────────────────────────

# ── Prompt loading — all industry knowledge lives in config/prompts/, not here ──
# To adapt haystacked for a new industry: edit the .txt files, no Python needed.

def _load_prompt(filename: str) -> str:
    p = Path(__file__).parent / "config" / "prompts" / filename
    return p.read_text(encoding="utf-8").strip()


def _fill(template: str, **kwargs) -> str:
    """Replace {key} placeholders in a prompt template without touching JSON braces.
    Uses explicit named replacement so JSON like {"field":null} is preserved."""
    for key, value in kwargs.items():
        template = template.replace("{" + key + "}", str(value) if value is not None else "")
    return template

MAIN_SYSTEM               = _load_prompt("basic_system.txt")
BASIC_USER_TEMPLATE       = _load_prompt("basic_template.txt")
DOMAIN_DETECTION_TEMPLATE = _load_prompt("domain_detection_template.txt")
CONTACT_SYSTEM       = _load_prompt("contact_system.txt")
CONTACT_USER_TEMPLATE= _load_prompt("contact_template.txt")
NACE_SYSTEM          = _load_prompt("nace_system.txt")
NACE_USER_TEMPLATE   = _load_prompt("nace_template.txt")
# AGV system prompt = extraction role + full industry README (loaded via context_builder)
# This gives the LLM domain knowledge about VNA, G2P, OEM rebadging, etc.
_DOMAIN_SYSTEM: dict[str, str] = {
    sid: build_system_context(domain_prefix=sid)
    for sid in _EXTRACTABLE_DOMAINS
}
EXTRACTION_USER_TEMPLATE = _load_prompt("extraction_template.txt")          # full fallback template
# Pass 4a: scope_classification_template.txt (Step 7); fall back to vehicle_type_template.txt
_scope_cls_path = _CONFIG_DIR / "prompts" / "scope_classification_template.txt"
SCOPE_CLASSIFICATION_TEMPLATE = (
    _load_prompt("scope_classification_template.txt")
    if _scope_cls_path.exists()
    else _load_prompt("vehicle_type_template.txt")
)
VEHICLE_TYPE_TEMPLATE = SCOPE_CLASSIFICATION_TEMPLATE  # alias for any remaining references
# Per-domain Pass 4a classification templates (one per domain, domain-specific leaves only)
_DOMAIN_CLASSIF_TEMPLATES: dict = {}
for _domain_sid in _shared_candidates:  # all domain-level scope_ids
    _slug = _domain_sid.lower().replace(":", "_")
    _tmpl_path = _CONFIG_DIR / "prompts" / f"classification_template_{_slug}.txt"
    if _tmpl_path.exists():
        _DOMAIN_CLASSIF_TEMPLATES[_domain_sid] = _tmpl_path.read_text(encoding="utf-8")
assert _DOMAIN_CLASSIF_TEMPLATES, (
    "No classification templates found for any extractable domain — "
    "run generate_all.py and check config/prompts/classification_template_*.txt"
)
# Pass 4b templates — derived from scope_registry.json scope nodes (Step 7)
_PRODUCT_TYPE_TEMPLATES = {
    node["canonical_name"]: _load_prompt(f"extraction_template_{node['tab_name'].lower().replace(' ', '_')}.txt")
    for node in _scope_reg["scopes"].values()
    if node.get("canonical_name") and node.get("tab_name")
    and (_CONFIG_DIR / "prompts" / f"extraction_template_{node['tab_name'].lower().replace(' ', '_')}.txt").exists()
}
# Fields determined in Pass 4a — excluded from 4b AP0 validation (loaded from vehicle_types.json)
_4A_SKIP = frozenset(_vehicle_cfg.get("4a_fields", []))
EXTRACTION_RETRY_SYSTEM   = _load_prompt("extraction_retry_system.txt")
EXTRACTION_RETRY_TEMPLATE = _load_prompt("extraction_retry_template.txt")


# ── AGV value validation ──────────────────────────────────────────────────────
# Loaded from config/plausibility.json (generated by scripts/generate_all.py from AP0 xlsx).
# Edit Plausibility Min/Max/Tender Unit columns in the AP0 xlsx — never hardcode here.
_plausibility_cfg = json.loads((_CONFIG_DIR / "plausibility.json").read_text()) \
    if (_CONFIG_DIR / "plausibility.json").exists() else {}

# Conversion keys used in the tender→supplier unit conversion (m→mm matching path).
# If plausibility.json loses these, app.py would KeyError at request time — catch it at startup.
for _conv_key in ("required_lifting_height_mm", "required_min_aisle_width_mm"):
    assert (_plausibility_cfg.get(_conv_key) or {}).get("conversion", {}).get("factor"), \
        f"plausibility.json missing {_conv_key}.conversion.factor — run generate_all.py"


def _to_match_units(criteria: dict) -> dict:
    """Convert domain_criteria values from stored units to matching-engine units.

    Reads conversion factors from _plausibility_cfg (AP0-generated).
    Only fields with a 'conversion' block are affected — all others pass through unchanged.
    Input values are assumed to be already normalized (post-validate_domain_criteria).
    """
    result = dict(criteria)
    for field, cfg in _plausibility_cfg.items():
        conv = cfg.get("conversion")
        if not conv:
            continue
        val = result.get(field)
        if val is None:
            continue
        factor = conv.get("factor")
        if factor and factor != 0:
            result[field] = int(float(val) / factor)
    return result


def validate_domain_criteria(crit: dict) -> tuple:
    """Returns (cleaned_dict, warnings_list).

    Auto-converts LLM unit errors (e.g. mm→m) using conversion rules from plausibility.json.
    Sets implausible values to None.
    """
    warnings = []
    cleaned = dict(crit)
    for field, cfg in _plausibility_cfg.items():
        val = cleaned.get(field)
        if val is None:
            continue
        try:
            v = float(val)
        except (TypeError, ValueError):
            continue

        lo, hi, unit, label = cfg["min"], cfg["max"], cfg["unit"], cfg["label"]
        conv = cfg.get("conversion")

        # Auto-convert using unit conversion rules from AP0 Unit Conversions sheet
        if conv and v > conv["threshold"]:
            v_converted = v * conv["factor"]
            if lo <= v_converted <= hi:
                warnings.append(
                    f"{label}: {v} {conv['llm_alias']} → {v_converted:.3g} {unit} (automatisch konvertiert)"
                )
                log.info("AGV unit conversion: %s %s → %s %s", label, v, v_converted, unit)
                cleaned[field] = v_converted
                continue

        if not (lo <= v <= hi):
            warnings.append(
                f"{label}: value {v} {unit} outside plausible range [{lo}–{hi} {unit}] → ignored"
            )
            log.warning("AGV-Plausibilität: %s", warnings[-1])
            cleaned[field] = None
    return cleaned, warnings


# ── PDF extraction ────────────────────────────────────────────────────────────
def extract_text_from_pdf(pdf_bytes: bytes) -> tuple[str, int]:
    with pdfplumber.open(io.BytesIO(pdf_bytes)) as pdf:
        num_pages = len(pdf.pages)
        pages = []
        for i, page in enumerate(pdf.pages):
            text = page.extract_text()
            log.debug("Seite %d: %d Z.", i + 1, len(text) if text else 0)
            if text:
                pages.append(text)
    full_text = "\n\n".join(pages)
    log.info("PDF: %d Seiten, %d Zeichen, %d Seiten mit Text", num_pages, len(full_text), len(pages))
    return full_text, num_pages


# ── Ollama call ───────────────────────────────────────────────────────────────
async def call_ollama(system: str, user: str, label: str) -> str:
    payload = {
        "model": OLLAMA_MODEL,
        "system": system,
        "prompt": user,
        "stream": False,
        "options": {"temperature": 0.0, "num_predict": 4096, "num_ctx": _OLLAMA_NUM_CTX},
    }
    log.info("Ollama [%s]: system=%d Z., prompt=%d Z.", label, len(system), len(user))
    t0 = datetime.now()
    async with httpx.AsyncClient(timeout=3600.0) as client:
        resp = await client.post(OLLAMA_URL, json=payload)
        resp.raise_for_status()
    elapsed = (datetime.now() - t0).total_seconds()
    raw = resp.json().get("response", "")
    log.info("Ollama [%s]: %.1fs, %d Z. Antwort", label, elapsed, len(raw))
    return raw


# ── SSE helper ────────────────────────────────────────────────────────────────
def sse(event: str, data: dict) -> str:
    return f"event: {event}\ndata: {json.dumps(data, ensure_ascii=False)}\n\n"


# ── D1 provenance helper ───────────────────────────────────────────────────────
def _attribute_nulls(before: dict, after: dict, cause: str, sink: dict, rejected: dict = None) -> None:
    """Record `cause` in `sink` for any key that had a non-null value in `before`
    and became None in `after` (dict-diff attribution for validate_tender_values()/
    validate_domain_criteria(), neither of which is modified by this — see D1 plan).
    `sink.setdefault` so an earlier attribution for the same key is never overwritten.
    If `rejected` is given, also captures the rejected (value, None) pair — these two
    validators have no source concept, so the source half is always None (F3).
    """
    for k, v in before.items():
        if v is not None and not str(k).endswith("_source") and not str(k).startswith("_") and after.get(k) is None:
            sink.setdefault(k, cause)
            if rejected is not None:
                rejected.setdefault(k, (v, None))


def _assemble_field_provenance(
    produced_by: dict, nulled_by: dict, rejected: dict,
    pre_4c_snapshot: dict, four_c_state: dict,
    rescued_fields: set = frozenset(),
) -> dict:
    """D1a (F3, test-coverage fix): assemble per-field provenance, keyed by tender_key,
    for build_tender_run(). Pure function of its arguments — does not touch
    domain_criteria/new_req or any other analyze() scope.

    `raw_value`/`raw_source` reflect the actually-rejected (value, source) pair
    (from `rejected`) when present — the true point-of-rejection data, which is
    the POST-4c state if Pass 4c overrode Pass 4b before the guard rejected it.
    Falls back to `pre_4c_snapshot` only when nothing was captured in `rejected`
    (e.g. a field that was never nulled, or nulled before any guard ran).

    `pre_4c_value`/`pre_4c_source` always reflect `pre_4c_snapshot`, regardless
    of what `rejected` holds — so when 4c overrode 4b and was itself rejected,
    the persisted record shows BOTH what 4b originally said AND what was
    actually rejected.

    `rescued_fields` (D0): tender_keys whose Layer-2 null was rescued by the
    source-span guard's value+unit adjacency check — these fields were NOT
    nulled (they don't appear in `nulled_by`/`rejected` at all), so this only
    adds a diagnostic note into the field's write-only `notes` key.
    """
    field_provenance: dict = {}
    for _tk in set(produced_by) | set(nulled_by) | set(pre_4c_snapshot) | set(rejected) | set(rescued_fields):
        _pre_4c_value, _pre_4c_source = pre_4c_snapshot.get(_tk, (None, None))
        if _tk in rejected:
            _raw_value, _raw_source = rejected[_tk]
        else:
            _raw_value, _raw_source = _pre_4c_value, _pre_4c_source
        _notes = None
        if _tk in rescued_fields:
            _notes = (
                "L2 rescue: citation was hint-echoed/unconfirmed but value+unit "
                "pair found in document text"
            )
        field_provenance[_tk] = {
            "produced_by": produced_by.get(_tk),
            "nulled_by":   nulled_by.get(_tk),
            "provenance": {
                "raw_value":      _raw_value,
                "raw_source":     _raw_source,
                "pre_4c_value":   _pre_4c_value,
                "pre_4c_source":  _pre_4c_source,
                "pass_4c_state":  four_c_state.get(_tk),
                # write-only: human-diagnostic only, never read/parsed by pipeline code.
                "notes":          _notes,
            },
        }
    return field_provenance


# ── Routes ────────────────────────────────────────────────────────────────────
@app.get("/", response_class=HTMLResponse)
async def index(request: Request):
    return templates.TemplateResponse("index.html", {"request": request})


@app.post("/analyze")
async def analyze(file: UploadFile = File(...)):
    filename  = file.filename
    pdf_bytes = await file.read()

    async def stream():
        t0 = datetime.now()
        log.info("=== Neue Analyse: %s ===", filename)

        yield sse("step", {"id": "upload", "status": "done", "message": f"'{filename}' received"})

        # D1: per-field extraction provenance — defaulted here so build_tender_run()
        # always receives well-formed data regardless of which branch below runs
        # (e.g. replay mode never populates these; they stay empty → all-None provenance).
        _produced_by: dict = {}
        _nulled_by: dict = {}
        _4c_state: dict = {}
        _pre_4c_snapshot: dict = {}
        # D1a (F3): actually-rejected (value, source) pair at the point the guard/
        # validator nulled it — reflects POST-4c state when 4c overrode 4b first.
        _rejected: dict = {}
        # D0: fields whose Layer-2 null was rescued (value+unit found in document
        # despite an unconfirmed citation) — defaulted here for the same reason
        # as the dicts above (replay mode never populates it).
        _l2_rescued_fields: set = set()

        is_replay = filename.lower().endswith(".json")

        if is_replay:
            # ── Replay mode: skip LLM, use cached extraction ──────────────────
            try:
                cached = json.loads(pdf_bytes.decode("utf-8"))
            except Exception as e:
                yield sse("error", {"message": f"Invalid JSON: {e}"}); return

            replay_vt       = cached.get("vehicle_type") or ""
            replay_criteria = read_run_criteria(cached)

            if not replay_vt or not replay_criteria:
                yield sse("error", {"message": "JSON must contain 'vehicle_type' and 'domain_criteria'."}); return

            yield sse("step", {"id": "extract", "status": "done",
                               "message": "Replay mode — LLM extraction skipped"})
            yield sse("log",  {"message": f"Loaded cached extraction: vehicle_type={replay_vt}, "
                                          f"{len(replay_criteria)} criteria fields"})

            canonical_product_type = _VT_MAP_CFG.get(replay_vt.lower().strip()) or replay_vt
            domain_criteria       = dict(replay_criteria)
            # D1a: every non-null field taken from the replayed source is attributed
            # to "replay" — mutually exclusive with the "4a"/4b/4c branches below
            # (this is the `if is_replay:` branch; those live in the `else:` path).
            _produced_by = {
                _k: "replay" for _k, _v in domain_criteria.items()
                if _v is not None and not str(_k).endswith("_source") and not str(_k).startswith("_")
            }
            text               = ""
            parse_method       = "replay"
            # Derive detected_domain from VT scope if not present (old captured files pre-date this field)
            _replay_domain = cached.get("detected_domain")
            if not _replay_domain and canonical_product_type:
                _leaf = _LEGACY_MAP.get(canonical_product_type, "")
                for _dom in _EXTRACTABLE_DOMAINS:
                    if _leaf.startswith(_dom):
                        _replay_domain = _dom
                        break
            result             = {
                "detected_domain": _replay_domain,
                "in_scope":    cached.get("in_scope", True),
                "buyer":       cached.get("buyer"),
                "project":     cached.get("project"),
                "contact":     cached.get("contact"),
                "summary":     cached.get("summary"),
                "nace_code":   cached.get("nace_code"),
                "nace_label":  cached.get("nace_label"),
            }
            analysis_id = str(uuid.uuid4())
            is_extractable = True

        elif filename.lower().endswith(".pdf"):
            size_kb = len(pdf_bytes) // 1024
            log.info("PDF-Größe: %d KB", size_kb)
            yield sse("log", {"message": f"PDF size: {size_kb} KB"})

            if len(pdf_bytes) > 20 * 1024 * 1024:
                yield sse("error", {"message": "PDF too large (max. 20 MB)."}); return

            # ── PDF extraction ────────────────────────────────────────────────────
            yield sse("step", {"id": "extract", "status": "running", "message": "Extracting text…"})
            await asyncio.sleep(0)

            try:
                text, num_pages = extract_text_from_pdf(pdf_bytes)
            except Exception as e:
                log.exception("PDF-Extraktion fehlgeschlagen")
                yield sse("error", {"message": f"PDF could not be read: {e}"}); return

            if not text.strip():
                yield sse("error", {"message": "No text found (scanned document?)"}); return

            # qwen2.5:7b has 128k token context; we activate 32k via num_ctx.
            # 50k chars ≈ 14k tokens — covers virtually all tender documents in full.
            max_chars = 50_000
            truncated = len(text) > max_chars
            if truncated:
                log.info("Text gekürzt: %d → %d Z.", len(text), max_chars)
                text = text[:max_chars] + "\n\n[... document truncated ...]"

            yield sse("step", {"id": "extract", "status": "done",
                                "message": f"{num_pages} pages · {len(text):,} characters" + (" · truncated" if truncated else "")})
            yield sse("log", {"message": f"Extrahiert: {num_pages} Seiten | {len(text):,} Z. | Gekürzt: {truncated}"})

            # ── LLM Step 1: Basic extraction ──────────────────────────────────────
            yield sse("step", {"id": "llm", "status": "running",
                                "message": f"Extracting basic data ({OLLAMA_MODEL})…"})
            await asyncio.sleep(0)

            # Use full available text for basic extraction so contact info
            # and summaries from later pages are visible to the model.
            basic_user = _fill(BASIC_USER_TEMPLATE, text=text)
            try:
                raw_basic = await call_ollama(MAIN_SYSTEM, basic_user, "basic")
            except httpx.ConnectError:
                yield sse("error", {"message": "Ollama not reachable — please run './start.sh'."}); return
            except Exception as e:
                log.exception("LLM-Fehler (basic)")
                yield sse("error", {"message": f"LLM error: {e}"}); return

            t1 = (datetime.now() - t0).total_seconds()
            yield sse("step", {"id": "llm", "status": "done", "message": f"LLM analysis done ({t1:.1f}s)"})
            yield sse("log", {"message": f"Grunddaten: {t1:.1f}s | {len(raw_basic)} Z."})

            yield sse("step", {"id": "parse", "status": "running", "message": "Antwort wird geparst…"})
            await asyncio.sleep(0)

            try:
                result = repair_and_parse(raw_basic)
            except ValueError as e:
                log.error("Parse-Fehler: %s", e)
                yield sse("step", {"id": "parse", "status": "error", "message": str(e)})
                yield sse("error", {"message": str(e), "raw_preview": raw_basic[:500]}); return

            parse_method = result.pop("_parse_method", "direct")

            # Clean up string "null" values the LLM sometimes emits instead of JSON null
            for k, v in result.items():
                if v == "null" or v == "NULL":
                    result[k] = None

            # ── Contact fallback: targeted pass on document tail ──────────────────
            # Contact info is often at the end of a document. If the main extraction
            # missed contact fields and the document has a meaningful tail, run a
            # short focused call on the last 4000 chars.
            contact_missing = not any(result.get(f) for f in _CONTACT_FALLBACK_TRIGGER)
            full_text_len = result.get("text_length", len(text))  # not set yet, use len(text)
            if contact_missing and len(text) > 6000:
                tail = text[-4000:]
                try:
                    raw_contact = await call_ollama(CONTACT_SYSTEM, _fill(CONTACT_USER_TEMPLATE, text=tail), "contact")
                    contact_data = repair_and_parse(raw_contact)
                    contact_data.pop("_parse_method", None)
                    for field in _CONTACT_FALLBACK_TARGET:
                        if contact_data.get(field) and not result.get(field):
                            result[field] = contact_data[field]
                            log.info("Kontakt-Fallback: %s = %s", field, contact_data[field])
                except Exception as e:
                    log.warning("Kontakt-Fallback fehlgeschlagen: %s", e)

            # ── LLM Step 2: NACE classification (short, targeted) ────────────────
            yield sse("step", {"id": "parse", "status": "running", "message": "NACE klassifizieren…"})
            # Fallback chain: tender_category → project_name → generic
            tender_cat = (result.get("tender_category")
                          or result.get("project_name")
                          or "unknown service")
            # Fallback chain: buyer_industry → buyer name → generic
            buyer_ind  = (result.get("buyer_industry")
                          or result.get("buyer")
                          or "unknown industry")
            nace_user  = _fill(NACE_USER_TEMPLATE,
                tender_category=tender_cat, buyer_industry=buyer_ind,
                category_list=CATEGORY_LIST
            )
            try:
                raw_nace = await call_ollama(NACE_SYSTEM, nace_user, "nace")
                nace_data = repair_and_parse(raw_nace)
                nace_data.pop("_parse_method", None)
                in_scope = nace_data.pop("in_scope", True)
                result.update(nace_data)
                result["in_scope"] = bool(in_scope)
                log.info("NACE: tender=%s in_scope=%s", result.get("nace_tender"), result["in_scope"])
            except Exception as e:
                log.warning("NACE-Klassifizierung fehlgeschlagen: %s", e)
                result["in_scope"] = True  # don't hide result on classification error

            t2 = (datetime.now() - t0).total_seconds()
            scope_label = "" if result.get("in_scope", True) else " · out of scope"
            yield sse("step", {"id": "parse", "status": "done",
                                "message": f"Parsing OK ({parse_method}) | NACE: {result.get('nace_tender','–')}{scope_label}"})
            yield sse("log", {"message": f"Parse+NACE: {t2:.1f}s gesamt"})

            # ── Pass 2b: Domain Detection ────────────────────────────────────────────
            yield sse("step", {"id": "parse", "status": "running", "message": "Domain wird erkannt…"})
            await asyncio.sleep(0)
            detected_domain = None
            try:
                domain_user = _fill(DOMAIN_DETECTION_TEMPLATE,
                                    tender_category=result.get("tender_category") or "",
                                    summary=result.get("summary") or "")
                raw_domain = await call_ollama(MAIN_SYSTEM, domain_user, "domain_detect")
                domain_data = repair_and_parse(raw_domain)
                domain_data.pop("_parse_method", None)
                detected_domain = domain_data.get("detected_domain")
                log.info("Domain Detection: detected_domain=%s", detected_domain)
            except Exception as e:
                log.warning("Domain Detection fehlgeschlagen: %s", e)

            # Keyword-Fallback: wenn LLM kein Ergebnis liefert
            if not detected_domain:
                text_lower = text[:5000].lower()
                for domain_id, kws in _DOMAIN_KWS.items():
                    if any(kw in text_lower for kw in kws):
                        detected_domain = domain_id
                        log.info("Domain Keyword-Fallback: %s", domain_id)
                        break  # Phase 3 TODO: replace with score-based selection

            result["detected_domain"] = detected_domain
            yield sse("step", {"id": "parse", "status": "done",
                                "message": f"Domain: {detected_domain or 'unbekannt'}"})
            yield sse("log", {"message": f"detected_domain={detected_domain}"})

            is_extractable = result.get("detected_domain") in _EXTRACTABLE_DOMAINS
            log.info("Domain erkannt: %s (is_extractable=%s)", result.get("detected_domain"), is_extractable)

            # ── LLM: AGV criteria extraction (if applicable) ──────────────────────
            domain_criteria = None
            matches = []
            matches_all = []
            canonical_product_type = None
            analysis_id = str(uuid.uuid4())

        else:
            yield sse("error", {"message": "Only PDF or JSON replay files are supported."}); return

        if not is_replay:
            matches = []
            matches_all = []

        if is_extractable and not is_replay:
            yield sse("step", {"id": "domain", "status": "running",
                                "message": "Produktkategorie wird klassifiziert…"})
            await asyncio.sleep(0)

            _domain = result.get("detected_domain")
            _is_single_leaf = _domain in _SINGLE_LEAF_DOMAINS

            if _is_single_leaf:
                # Single-leaf domain: every scope_variant maps to the same canonical_name/leaf
                # (verified via scope_registry.json variant_map/legacy_map) — Pass 4a's LLM
                # call can never change the outcome, so skip it entirely (OI-107).
                canonical_product_type = _scope_reg["scopes"][_domain]["canonical_name"]
                vt_criteria = {"required_product_type": canonical_product_type}
                log.info("Pass 4a skipped (single-leaf domain %s): vehicle_type=%s",
                          _domain, canonical_product_type)
            else:
                # ── Pass 4a: classify vehicle type only ───────────────────────────
                _classif_tmpl = _DOMAIN_CLASSIF_TEMPLATES.get(
                    result.get("detected_domain"), SCOPE_CLASSIFICATION_TEMPLATE
                )
                vt_user = _fill(_classif_tmpl, text=text)
                vt_criteria: dict = {}
                _ap0_violations_4a: dict = {}
                try:
                    for _attempt in range(3):
                        if _attempt == 0:
                            raw_vt = await call_ollama(_DOMAIN_SYSTEM[result.get("detected_domain")], vt_user, "agv_4a")
                            try:
                                vt_criteria = repair_and_parse(raw_vt)
                            except ValueError:
                                log.warning("4a-Antwort kein JSON — Retry")
                                yield sse("log", {"message": "4a: Kein JSON → Retry…"})
                                raw_vt2 = await call_ollama(EXTRACTION_RETRY_SYSTEM,
                                                            _fill(EXTRACTION_RETRY_TEMPLATE, text=text), "agv_4a_retry")
                                vt_criteria = repair_and_parse(raw_vt2)
                        else:
                            correction_user = _build_correction_prompt(_ap0_violations_4a, text)
                            raw_vt = await call_ollama(EXTRACTION_RETRY_SYSTEM, correction_user,
                                                       f"agv_4a_correction{_attempt}")
                            try:
                                correction = repair_and_parse(raw_vt)
                            except ValueError:
                                correction = {}
                            for _tk in _ap0_violations_4a:
                                if _tk in correction:
                                    vt_criteria[_tk] = correction[_tk]

                        vt_criteria.pop("_parse_method", None)
                        for k, v in list(vt_criteria.items()):
                            if v in ("null", "NULL", "None", "none", "N/A", "n/a", ""):
                                vt_criteria[k] = None

                        # Only validate required_product_type in 4a — use domain-specific values, not AP0 enum.
                        # AP0 allowed_values for product_type = @SCOPE_CANONICAL_NAMES (excludes IK scope_variants
                        # like "Process Cooling"). _DOMAIN_CLASSIF_VALUES is correct for all domains.
                        _raw_4a = vt_criteria.get("required_product_type")
                        _domain_vals = _DOMAIN_CLASSIF_VALUES.get(result.get("detected_domain"), frozenset())
                        if _raw_4a and _domain_vals and _raw_4a not in _domain_vals:
                            _ap0_violations_4a = {"required_product_type": (_raw_4a, sorted(_domain_vals))}
                        else:
                            _ap0_violations_4a = {}
                        if not _ap0_violations_4a:
                            break

                        _bad = list(_ap0_violations_4a.values())[0][0]
                        _allowed = list(_ap0_violations_4a.values())[0][1]
                        _msg = (f"required_product_type='{_bad}' invalid "
                                f"(allowed: {' / '.join(_allowed)}) — attempt {_attempt + 1}/3")
                        log.warning(_msg)
                        yield sse("log", {"message": f"⚠ {_msg}"})
                        if _attempt == 2:
                            yield sse("warning", {"field": "required_product_type",
                                                  "message": f"{_msg} — keyword fallback used"})

                except Exception as e:
                    log.exception("Pass 4a fehlgeschlagen")
                    yield sse("log", {"message": f"⚠ 4a error: {e} — keyword fallback"})

                # Normalize vehicle type from 4a result
                raw_vt_str = vt_criteria.get("required_product_type") or ""
                if isinstance(raw_vt_str, list):
                    raw_vt_str = next(
                        (item for item in raw_vt_str if _VT_MAP_CFG.get(str(item).lower().strip())),
                        raw_vt_str[0] if raw_vt_str else ""
                    ) or ""
                raw_vt_lower = str(raw_vt_str).lower().strip()
                canonical_product_type = _VT_MAP_CFG.get(raw_vt_lower) or product_type_keyword_fallback(text or "")

                for override in _VT_OVERRIDES:
                    if override.get("regex") and re.search(override["regex"], text or ""):
                        if override.get("canonical"):
                            canonical_product_type = override["canonical"]
                        break

            log.info("Pass 4a: vehicle_type=%s", canonical_product_type)
            # Pre-compute 4c field set now that vehicle type is known; needed for progress total
            _leaf_scope = _LEGACY_MAP.get(canonical_product_type, "")
            _4c_scopes  = frozenset(_RESOLUTION_ORDER.get(_leaf_scope, []))
            _4c_fields = {
                k: v for k, v in _NUMERIC_KO_FIELD_HINTS.items()
                if v["scope"] in _4c_scopes
            }
            _4a_calls = 0 if _is_single_leaf else 1
            _agv_total = 1 + _4a_calls + len(_4c_fields)   # 4a(0 or 1) + 4b(1) + N×4c
            yield sse("step", {"id": "domain", "status": "running",
                                "message": f"Kategorie: {canonical_product_type} — Kriterien werden extrahiert…",
                                "done": _4a_calls, "total": _agv_total})
            await asyncio.sleep(0)

            # ── Pass 4b: extract type-specific fields ─────────────────────────
            _TEXT_TOKEN_ESTIMATE = len(text) // 4
            _FIXED_OVERHEAD_TOKENS = 10_100  # domain system prompt (~5500) + 4b template (~4600)
            _TOTAL_ESTIMATE = _TEXT_TOKEN_ESTIMATE + _FIXED_OVERHEAD_TOKENS
            if _TOTAL_ESTIMATE > _OLLAMA_NUM_CTX:
                yield sse("log", {
                    "message": (
                        f"⚠ Document too large for reliable extraction "
                        f"(~{_TOTAL_ESTIMATE:,} tokens estimated, limit: {_OLLAMA_NUM_CTX:,}). "
                        f"Please upload only the technical specification section "
                        f"(typically 5–15 pages) instead of the full tender document. "
                        f"Results may be incomplete."
                    )
                })

            template_4b = _PRODUCT_TYPE_TEMPLATES.get(canonical_product_type, EXTRACTION_USER_TEMPLATE)
            agv_user_4b = _fill(template_4b, text=text,
                                vehicle_type=canonical_product_type)

            domain_criteria: dict = {}
            _ap0_warnings: list = []
            _ap0_violations: dict = {}
            try:
                for _attempt in range(3):
                    if _attempt == 0:
                        raw_agv = await call_ollama(_DOMAIN_SYSTEM[result.get("detected_domain")], agv_user_4b, "agv_4b")
                        try:
                            domain_criteria = repair_and_parse(raw_agv)
                        except ValueError:
                            log.warning("4b-Antwort kein JSON — Retry mit typ-spezifischem Template")
                            yield sse("log", {"message": "4b: Kein JSON → Retry mit typ-spezifischem Template…"})
                            raw_agv2 = await call_ollama(EXTRACTION_RETRY_SYSTEM, agv_user_4b, "agv_4b_retry")
                            domain_criteria = repair_and_parse(raw_agv2)
                    else:
                        correction_user = _build_correction_prompt(_ap0_violations, text)
                        raw_agv = await call_ollama(EXTRACTION_RETRY_SYSTEM, correction_user,
                                                    f"agv_4b_correction{_attempt}")
                        try:
                            correction = repair_and_parse(raw_agv)
                        except ValueError:
                            log.warning("4b AP0-Korrektur kein JSON — Versuch %d/3", _attempt + 1)
                            correction = {}
                        for _tk in _ap0_violations:
                            if _tk in correction:
                                domain_criteria[_tk] = correction[_tk]

                    domain_criteria.pop("_parse_method", None)
                    for k, v in list(domain_criteria.items()):
                        if v in ("null", "NULL", "None", "none", "N/A", "n/a", ""):
                            domain_criteria[k] = None

                    # AP0 validation for 4b fields — skip fields already validated in 4a
                    _ap0_violations = _find_invalid_ap0_fields(domain_criteria, skip=_4A_SKIP)
                    if not _ap0_violations:
                        break

                    _viol_summary = "; ".join(
                        f"{tk}='{bad}' (allowed: {', '.join(av)})"
                        for tk, (bad, av) in _ap0_violations.items()
                    )
                    log.warning("4b AP0-Feldvalidierung Versuch %d/3: %s", _attempt + 1, _viol_summary)
                    yield sse("log", {"message": f"AP0 field validation attempt {_attempt + 1}/3: {_viol_summary}"})
                    if _attempt == 2:
                        _ap0_warnings = [
                            f"{tk}: '{bad}' not a valid AP0 value after 3 attempts "
                            f"(allowed: {', '.join(av)}) — field ignored"
                            for tk, (bad, av) in _ap0_violations.items()
                        ]

                for w in _ap0_warnings:
                    log.error("AP0-Feldvalidierung: %s", w)
                    _tk = w.split(":")[0]
                    yield sse("warning", {"field": _tk, "message": w})

            except Exception as e:
                log.exception("Pass 4b fehlgeschlagen")
                yield sse("log", {"message": f"⚠ 4b Fehler: {e}"})

            # D1: snapshot numeric-KO fields as 4b left them, before Pass 4c / the
            # source-span guard can overwrite or null them — recoverable for forensics.
            _pre_4c_snapshot = {
                _k: (domain_criteria.get(_k), domain_criteria.get(f"{_k}_source"))
                for _k in _NUMERIC_KO_TENDER_KEYS
            }
            # D1: every non-null field present after 4b is (so far) attributed to 4b;
            # Pass 4c below overrides individual entries when it returns a value.
            _produced_by = {
                _k: "4b" for _k, _v in domain_criteria.items()
                if _v is not None and not str(_k).endswith("_source") and not str(_k).startswith("_")
            }

            yield sse("step", {"id": "domain", "status": "running",
                                "message": "Pass 4b: Batch-Extraktion abgeschlossen",
                                "done": _4a_calls + 1, "total": _agv_total})
            await asyncio.sleep(0)

            # ── Pass 4c: per-field extraction for numeric KO fields ──────────────
            # Each numeric KO field gets its own focused LLM call (one field + document).
            # Shorter prompt → more attention budget per field → fewer inference hallucinations.
            # Results override 4b values; source-span enforcement (below) still applies.
            # canonical_product_type == AP0 sheet name ("Forklift AGV", "Tugger AGV", "Mobile AMR")
            if _4c_fields:
                yield sse("step", {"id": "domain", "status": "running",
                                   "message": f"Pass 4c: {len(_4c_fields)} numerische Felder einzeln…",
                                   "done": _4a_calls + 1, "total": _agv_total})
                await asyncio.sleep(0)
                _4c_count    = 0
                _4c_abstained: set = set()   # fields where 4c returned null (used in enforcement below)
                for _4c_i, (_fk, _fmeta) in enumerate(_4c_fields.items(), start=1):
                    # Semantic definition only — NULL RULE / CONSERVATIVE EXTRACTION prose stripped
                    # to avoid tripling the null-bias already present in the system prompt.
                    _fhint_full = _fmeta["hint"]
                    _fhint_def  = strip_null_rule(_fhint_full)
                    _per_user = (
                        f"Vehicle type: {canonical_product_type}.\n\n"
                        f"Find the value of '{_fk}' in the tender document.\n\n"
                        f"Field meaning: {_fhint_def}\n\n"
                        f"Step 1: Scan the document for any sentence, table cell, or labelled line "
                        f"that states this value directly.\n"
                        f"Step 2: If found, copy it verbatim as the source and extract the number "
                        f"(note: commas in numbers are thousands separators — '1,000' means 1000). "
                        f"{_4C_EXTRACTION_DIRECTION.get(_fk, '')}\n"
                        f"Step 3: If not found anywhere in the document text, output null for both "
                        f"— do NOT infer from vehicle type, warehouse layout, or industry standards.\n\n"
                        f"DOCUMENT:\n{text}\n\n"
                        f"Output ONLY this JSON:\n"
                        f'{{"{_fk}": <number or null>, "{_fk}_source": "<verbatim quote or null>"}}'
                    )
                    try:
                        _per_raw    = await call_ollama(_DOMAIN_SYSTEM[result.get("detected_domain")], _per_user, f"agv_4c_{_fk}")
                        _per_parsed = repair_and_parse(_per_raw)
                        if _fk in _per_parsed:
                            _4c_val = _per_parsed[_fk]
                            _4c_src = _per_parsed.get(f"{_fk}_source")
                            if _4c_val is not None:
                                # 4c found a value → use it (focused extraction wins)
                                domain_criteria[_fk]              = _4c_val
                                domain_criteria[f"{_fk}_source"]  = _4c_src
                                _4c_count += 1
                                _4c_state[_fk] = "returned_value"
                                _produced_by[_fk] = "4c"
                            else:
                                # 4c explicitly returned null → abstained
                                _4c_abstained.add(_fk)
                                _4c_state[_fk] = "explicit_null"
                            log.debug("4c %s: %s (src: %s)", _fk, _4c_val,
                                      str(_4c_src or "")[:60])
                        else:
                            # Field key absent from parsed dict (regex-fallback path) → abstained
                            _4c_abstained.add(_fk)
                            _4c_state[_fk] = "key_absent"
                            log.debug("4c %s: field absent in parse result → abstained", _fk)
                    except Exception as _pe:
                        # Parse or call failure → abstained so L2 can still check 4b value
                        _4c_abstained.add(_fk)
                        _4c_state[_fk] = "parse_error"
                        log.warning("4c '%s' fehlgeschlagen (→ abstained): %s", _fk, _pe)
                    yield sse("step", {"id": "domain", "status": "running",
                                       "message": f"Pass 4c ({_4c_i}/{len(_4c_fields)})",
                                       "done": _4a_calls + 1 + _4c_i, "total": _agv_total})
                    await asyncio.sleep(0)
                log.info("Pass 4c: %d Felder neu extrahiert, %d abstained",
                         _4c_count, len(_4c_abstained))

            # ── Source-span enforcement (generic, field-agnostic) ────────────────
            # Layer 1: source absent/null → LLM had no explicit source → null value.
            # Layer 0: source present but not grounded in the real document → null
            #   (catches a fabricated value with a fabricated-but-self-consistent
            #   quote; runs unconditionally, not scoped to 4c abstention).
            # Layer 2 (scoped to 4c abstentions): 4c said null AND 4b source doesn't
            #   numerically confirm the value → 4b was likely hallucinating → null value,
            #   UNLESS the value's digit-string occurs in the real document adjacent to
            #   its unit token (D0 fix) — that rescues values whose citation channel is
            #   broken (e.g. Pass 4b echoing the AP0 hint as `_source`) but which are
            #   otherwise genuinely present in the document.
            # See src/json_repair.py::enforce_source_spans for the full logic.
            _4c_abstained_ref = _4c_abstained if _4c_fields else set()
            domain_criteria, _span_messages, _span_events = enforce_source_spans(
                domain_criteria, text, _NUMERIC_KO_TENDER_KEYS, _4c_abstained_ref, units=_NUMERIC_KO_FIELD_UNITS
            )
            for _msg in _span_messages:
                yield sse("log", {"message": _msg})
            # D1: attribute each nulled field to the guard layer that nulled it.
            # D1a (F3): also capture the actually-rejected (value, source) pair —
            # this is the POST-4c state if 4c overrode 4b before the guard ran.
            # D0: a rescue is NOT a null — filter it out here so it never enters
            # _nulled_by (which build_tender_run() asserts against the closed
            # _NULLED_BY_VALUES vocabulary in src/tender_store.py) or _rejected
            # (the value was kept, not rejected). Track rescued fields separately
            # for the provenance "notes" annotation below.
            for _ev in _span_events:
                if _ev.layer == "L2_RESCUED":
                    _l2_rescued_fields.add(_ev.field)
                    continue
                _nulled_by[_ev.field] = _ev.layer
                _rejected[_ev.field] = (_ev.value, _ev.source)

            # Merge 4a results into domain_criteria
            # D1a (F2): "4a" is a pipeline-STAGE tag, not "LLM was called" — it
            # covers both the Pass-4a LLM-classification sub-path and the OI-107
            # single-leaf-domain shortcut sub-path (_is_single_leaf, no LLM call).
            # The finer LLM-vs-shortcut distinction is preserved separately in the
            # debug log ("Pass 4a skipped (single-leaf domain %s)...").
            _merged_product_type = vt_criteria.get("required_product_type")
            domain_criteria["required_product_type"] = _merged_product_type
            if _merged_product_type is not None:
                _produced_by["required_product_type"] = "4a"

        if is_extractable:
            # Validate against AP0 allowed_values — reject values not in the allowed list
            from src.matching import validate_tender_values
            _before_av = dict(domain_criteria)
            domain_criteria, av_warnings = validate_tender_values(domain_criteria)
            _attribute_nulls(_before_av, domain_criteria, "allowed_values", _nulled_by, _rejected)
            for w in av_warnings:
                log.info("AP0 allowed_values filter: %s", w)
                yield sse("log", {"message": f"⚠ AP0-Filter: {w}"})

            # Validate plausibility — set implausible values to null
            _before_pl = dict(domain_criteria)
            domain_criteria, val_warnings = validate_domain_criteria(domain_criteria)
            _attribute_nulls(_before_pl, domain_criteria, "plausibility", _nulled_by, _rejected)
            if val_warnings:
                for w in val_warnings:
                    yield sse("log", {"message": f"⚠ Plausibility: {w}"})
            domain_criteria["_validation_warnings"] = val_warnings

            log.info("AGV-Kriterien (validiert): %s", json.dumps(domain_criteria, ensure_ascii=False)[:300])

            # Field text fallbacks: apply regex-based overrides for fields the LLM missed.
            # Rules loaded from config/vehicle_types.json → field_text_fallbacks (AP0-driven).
            for _fb in _FIELD_TEXT_FALLBACKS:
                _key  = _fb.get("tender_key")
                _rgx  = _fb.get("regex")
                _val  = _fb.get("value")
                if not _key or not _rgx or not _val:
                    continue
                if _fb.get("only_if_null") and domain_criteria.get(_key) is not None:
                    continue
                if re.search(_rgx, text or ""):
                    domain_criteria[_key] = _val
                    # D1: fallback re-produced this field — it's no longer "nulled" by
                    # whatever guard/validation nulled it earlier.
                    _produced_by[_key] = "fallback"
                    _nulled_by.pop(_key, None)
                    log.info("Field-text-fallback: %s = %s (regex: %s)", _key, _val, _rgx)

            # Run matching against SQLite supplier records
            # canonical_product_type already set in Pass 4a;
            # re-derive here as safety net (idempotent for valid values).
            raw_vt = domain_criteria.get("required_product_type") or ""
            if isinstance(raw_vt, list):
                raw_vt = next(
                    (item for item in raw_vt if _VT_MAP_CFG.get(str(item).lower().strip())),
                    raw_vt[0] if raw_vt else "",
                ) or ""
            raw_vt_lower = str(raw_vt).lower().strip()
            canonical_product_type = _VT_MAP_CFG.get(raw_vt_lower) or canonical_product_type

            _domain_for_override = result.get("detected_domain") if is_extractable else None
            if _domain_for_override not in _SINGLE_LEAF_DOMAINS:
                for override in _VT_OVERRIDES:
                    if override.get("regex") and re.search(override["regex"], text or ""):
                        if override.get("canonical"):
                            canonical_product_type = override["canonical"]
                        break

            # Split navigation string into list (e.g. "SLAM, QR Code" → ["SLAM", "QR Code"])
            raw_nav = domain_criteria.get("required_navigation_type") or ""
            nav_list = [n.strip() for n in raw_nav.replace(";", ",").split(",") if n.strip()] if raw_nav else []

            new_req = dict(domain_criteria)
            new_req["required_product_type"] = canonical_product_type
            # write canonical value back so result["domain_criteria"] JSON is consistent
            domain_criteria["required_product_type"] = canonical_product_type
            new_req["required_navigation_type"] = nav_list

            new_req = _to_match_units(new_req)

            # D1: assemble per-field provenance, keyed by tender_key, for build_tender_run().
            _field_provenance = _assemble_field_provenance(
                _produced_by, _nulled_by, _rejected, _pre_4c_snapshot, _4c_state, _l2_rescued_fields
            )

            # Phase 3: persist extraction run
            _tender_run = build_tender_run(
                run_id       = analysis_id,
                source_file  = filename,
                new_req      = new_req,
                domain_criteria = domain_criteria,
                result       = result,
                vehicle_type = canonical_product_type,
                in_scope     = bool(result.get("in_scope", False)),
                field_provenance = _field_provenance,
            )
            matches_raw, matches_all_raw = match_suppliers_new(
                TenderRequirements(_tender_run), _SUPPLIERS, top_n=5
            )
            matches     = [r.to_dict() for r in matches_raw]
            matches_all = [r.to_dict() for r in matches_all_raw]
            log.info("Matching: Top-Match %s (Score %d)", matches[0]["product"] if matches else "–",
                     matches[0]["score"] if matches else 0)
            persist_tender_run(_tender_run, match_results=matches_all_raw)

            yield sse("step", {"id": "domain", "status": "done",
                                "message": f"AGV-Analyse fertig · Top-Match: {matches[0]['product'] if matches else '–'}"})
            yield sse("log", {"message": f"AGV-Kriterien extrahiert | Top-Score: {matches[0]['score'] if matches else 0} | {len(matches_all)} Supplier bewertet"})

        # ── Final result ──────────────────────────────────────────────────────
        total = (datetime.now() - t0).total_seconds()
        result["filename"]               = filename
        result["text_length"]            = len(text)
        result["duration_s"]             = round(total, 1)
        result["parse_method"]           = parse_method
        result["domain_criteria"]        = domain_criteria
        result["matches"]                = matches
        result["matches_all"]            = matches_all if matches_all else []
        result["vehicle_type_canonical"] = canonical_product_type

        yield sse("log", {"message": f"Gesamt: {total:.1f}s"})
        result["analysis_id"] = analysis_id
        _analyses[analysis_id] = result
        yield sse("result", result)
        log.info("=== Fertig: %s in %.1fs ===", filename, total)

    return StreamingResponse(stream(), media_type="text/event-stream",
                             headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"})


@app.get("/db-status")
async def db_status():
    return {
        "sqlite_available": True,
        "supplier_count":   len(_SUPPLIERS),
        "message": "Using SQLite matching engine",
    }


@app.post("/match")
async def match_endpoint(request: Request):
    """Direct matching API — accepts structured tender requirements JSON."""
    if not _SUPPLIERS:
        return JSONResponse({"error": "No supplier records loaded. Run sync_airtable.py first."}, status_code=503)
    body = await request.json()
    top_raw, all_raw = match_suppliers_new(
        TenderRequirements.from_dict(_criteria_to_uuid_keyed(body)), _SUPPLIERS, top_n=10
    )
    top = [r.to_dict() for r in top_raw]
    all_results = [r.to_dict() for r in all_raw]
    return {"top": top, "all": all_results, "total": len(all_results)}


@app.post("/rematch")
async def rematch_endpoint(request: Request):
    """Re-run matching after user clarification or edit-panel override.

    Accepts {"analysis_id": "<uuid>", "overrides": {"lifting_height_mm": 12000, ...}} —
    db_keys with values in storage units. Uses the server-side cached domain_criteria as
    base so all previously extracted KO fields are preserved.
    Updates _analyses[analysis_id] so /api/last-result stays in sync.
    Returns 400 if analysis_id is not found in _analyses.
    """
    body = await request.json()
    analysis_id = body.get("analysis_id")
    overrides = body.get("overrides", {})
    new_vt = body.get("vehicle_type")

    if analysis_id and analysis_id in _analyses:
        cached = _analyses[analysis_id]
    elif not analysis_id and _analyses:
        # Backward-compat: no analysis_id supplied — use the most recently stored result
        cached = next(reversed(_analyses.values()))
    else:
        return JSONResponse({"error": "No analysis to rematch."}, status_code=400)

    criteria = dict(cached.get("domain_criteria", {}))
    for field_name, value in overrides.items():
        _fn_specs = _FIELDS_BY_FIELD_NAME.get(field_name, [])
        tender_key = _fn_specs[0].tender_key if _fn_specs and _fn_specs[0].tender_key else field_name
        # Normalize empty string → None (empty field in dialog = remove requirement)
        criteria[tender_key] = None if isinstance(value, str) and not value.strip() else value

    old_vt = cached.get("vehicle_type_canonical")
    if new_vt and new_vt in _VALID_VTS:
        criteria["required_product_type"] = new_vt
        cached["vehicle_type_canonical"] = new_vt

    if new_vt and new_vt in _VALID_VTS and new_vt != old_vt:
        for tender_key in list(criteria.keys()):
            if tender_key.startswith('_') or tender_key.endswith('_source'):
                continue  # never touch match-mechanics keys
            _tk_specs = _FIELDS_BY_TENDER_KEY.get(tender_key, [])
            scope     = _tk_specs[0].scope if _tk_specs else None
            old_scope = _LEGACY_MAP.get(old_vt, "")
            if scope and old_scope and scope == old_scope:
                del criteria[tender_key]

    # Apply same unit-conversion + plausibility logic as main flow — handles mm→m input from dialog
    criteria, _ = validate_domain_criteria(criteria)

    top_raw, all_raw = match_suppliers_new(
        TenderRequirements.from_dict(_criteria_to_uuid_keyed(_to_match_units(criteria))),
        _SUPPLIERS, top_n=10
    )
    top = [r.to_dict() for r in top_raw]
    all_results = [r.to_dict() for r in all_raw]

    cached["matches"]         = top
    cached["matches_all"]     = all_results
    cached["domain_criteria"] = criteria

    return {"top": top, "all": all_results, "total": len(all_results),
            "analysis_id": cached.get("analysis_id"),
            "domain_criteria": criteria}


@app.get("/api/field-meta")
async def field_meta():
    """Return AP0 field metadata for the frontend — labels, levels, data types, and sheet (vehicle-type group).
    Built from config/fields.json (generated from AP0 xlsx by generate_all.py)."""
    fields = load_fields()
    _UNITS = {"_kg":"kg","_mm":"mm","_pct":"%","_h":"h","_ms":"m/s",
              "_c":"°C","_eur":"EUR","_min":"min","_m":"m","_deg":"°"}
    _ABBR = {"Agv":"AGV","Amr":"AMR","Vda":"VDA","Vda5050":"VDA 5050","Wms":"WMS","Oem":"OEM",
             "Ko":"KO","Ui":"UI","Id":"ID","Ip":"IP","Fps":"FPS","Roi":"ROI",
             "Cop":"COP","Ik":"IK","Ped":"PED","Atex":"ATEX"}
    def _label(key: str, ap0_unit=None, override=None) -> str:
        # OI-100: AP0 "Display Label" column overrides the abbreviation heuristic below.
        if override:
            return override
        k = key
        # Prefer AP0 unit over suffix heuristic — avoids "_mm" label when storage is actually "m"
        unit = ap0_unit
        for suf, u in _UNITS.items():
            if k.endswith(suf):
                k = k[:-len(suf)]
                if unit is None:
                    unit = u
                break
        words = [_ABBR.get(w.capitalize(), w.capitalize()) for w in k.replace("_", " ").split()]
        label = " ".join(words)
        return f"{label} ({unit})" if unit else label
    # scope → sheet: canonical_name for leaf nodes, tab_name for domain-shared nodes, None for Global ("*")
    scope_to_sheet: dict[str, str | None] = {
        sid: None if sid == "*" else (node.get("canonical_name") or node.get("tab_name"))
        for sid, node in _scope_reg["scopes"].items()
    }
    # shared_sheet_name: tab_name of the domain-shared node (child of "*" with no canonical_name)
    shared_sheet_name: str = next(
        (n.get("tab_name", "") for n in _scope_reg["scopes"].values()
         if n.get("parent") == "*" and not n.get("canonical_name")),
        "",
    )

    meta = {}
    clones = {}
    seen_field_names: set = set()
    for spec in fields.values():
        db_key = spec.field_name
        if db_key in seen_field_names:
            continue  # first occurrence wins for duplicate field_names across VT sheets
        seen_field_names.add(db_key)
        tender_key = spec.tender_key
        entry = {
            "label":          _label(db_key, spec.unit, spec.display_label),
            "tender_key":     tender_key,
            "entity":         spec.entity,
            "level":          spec.level,
            "data_type":      spec.data_type,
            "operator":       spec.operator,
            "allowed_values": spec.allowed_values,
            "scope":          spec.scope,
            "sheet":          scope_to_sheet.get(spec.scope),
            "display_mode":      spec.display_mode or "editable",
            "user_description":  spec.user_description,
        }
        meta[db_key] = entry
        if tender_key and tender_key != db_key:
            # Clone entry keyed by tender_key — used for label lookups by tender_key in the frontend.
            clones[tender_key] = {**entry, "label": _label(tender_key, spec.unit, spec.display_label)}
    meta.update(clones)

    # Build per-domain descriptor for the DB browser domain filter
    _domains: list[dict] = []
    for _sid, _node in _scope_reg["scopes"].items():
        if _node.get("parent") != "*":
            continue
        # Short label: canonical_name if present, else strip "_Shared" from tab_name
        if _node.get("canonical_name"):
            _label_dom = _node["canonical_name"]
        elif _node.get("tab_name", "").endswith("_Shared"):
            _label_dom = _node["tab_name"][:-len("_Shared")]
        else:
            _label_dom = _sid.split(":")[-1]
        # Child leaves → VT names / product_type values
        _children = sorted(
            n["canonical_name"]
            for n in _scope_reg["scopes"].values()
            if n.get("parent") == _sid and n.get("canonical_name")
        )
        _pt = _children if _children else ([_node["canonical_name"]] if _node.get("canonical_name") else [])
        # All sheets for this domain (shared + leaf sheets)
        _dom_sheets = [s for s in [scope_to_sheet.get(_sid)] if s]
        for _cs, _cn in _scope_reg["scopes"].items():
            if _cn.get("parent") == _sid:
                _s = scope_to_sheet.get(_cs)
                if _s:
                    _dom_sheets.append(_s)
        _domains.append({
            "id":            _sid,
            "label":         _label_dom,
            "product_types": _pt,
            "vt_names":      _children,
            "shared_sheet":  scope_to_sheet.get(_sid) if _children else None,
            "sheets":        _dom_sheets,
        })

    # VT config for frontend column grouping — read entirely from generated config files
    meta["__vt_config__"] = {
        "extractable_domains": sorted(_EXTRACTABLE_DOMAINS),
        "legacy_map":    _LEGACY_MAP,
        "vehicle_types": list(_VALID_VTS),
        "shared_sheet_name": shared_sheet_name,
        "domains":       _domains,
    }
    return meta


@app.get("/health")
async def health():
    try:
        async with httpx.AsyncClient(timeout=3.0) as client:
            r = await client.get("http://localhost:11434/api/tags")
            models = [m["name"] for m in r.json().get("models", [])]
        model_ok = OLLAMA_MODEL in models
        return {
            "status": "ok" if model_ok else "degraded",
            "ollama": "running",
            "model": OLLAMA_MODEL,
            "model_available": model_ok,
            "models": models,
        }
    except Exception:
        return {"status": "degraded", "ollama": "not reachable", "model_available": False}


@app.get("/debug-page", response_class=HTMLResponse)
async def debug_page(request: Request):
    return templates.TemplateResponse("debug.html", {"request": request})


@app.get("/db", response_class=HTMLResponse)
async def db_page(request: Request):
    return templates.TemplateResponse("db.html", {"request": request})


@app.get("/api/last-result")
async def last_result():
    if not _analyses:
        return JSONResponse({"error": "No analysis result available yet."}, status_code=404)
    return next(reversed(_analyses.values()))


@app.get("/api/suppliers")
async def suppliers_list():
    """Return all supplier records.

    Column set and order are driven entirely by config/sqlite_schema.json
    (generated from AP0 xlsx by generate_all.py).  No field names are
    hardcoded here — adding a new VT sheet to AP0 automatically surfaces
    its fields without touching this file.
    """
    if not _SUPPLIERS:
        return JSONResponse({"error": "Database not available."}, status_code=503)

    import dataclasses as _dc

    _ext_cols = _EXT_COLUMNS  # loaded once at startup from AP0-generated sqlite_schema.json
    # Internal join keys never exposed to the frontend.
    _EXT_INTERNAL = {"extension_id", "base_model_id", "extra_fields"}
    # Product dataclass fields that are internal / already in the identity prefix.
    _PROD_SKIP = {
        "company_id", "base_model_id", "is_oem_product", "active",
        "product_description", "product_id", "company_name", "product_name", "product_type",
    }

    out = []
    for sr in _SUPPLIERS:
        p = sr.product
        # Identity prefix — always first so frontend sticky columns are stable.
        row: dict = {
            "product_id":   p.product_id,
            "company_name": p.company_name,
            "product_name": p.product_name,
            "description":  p.product_description,
        }
        # All AP0 fields from values dict — covers Base Model, Product, and Company entities.
        for uuid, fv in sr.values.items():
            col = fv.spec.field_name
            if col in _EXT_INTERNAL or col in row:
                continue
            row[col] = fv.value
        # Product-only commercial fields not captured by the values loop
        # (e.g. min_project_value_eur, max_project_value_eur).
        for f in _dc.fields(p):
            if f.name not in _PROD_SKIP and f.name not in row:
                row[f.name] = getattr(p, f.name)
        out.append(row)
    return out
