"""
AP-I1 — Data Loader
Loads SupplierRecords from SQLite via a 3-way JOIN.
Parsing rules per spec v1.2 LL-06 and Blank != Zero principle.

Field values are UUID-keyed via FieldValue. Field names, types, and entity routing
come from config/fields.json (generated by generate_all.py from AP0 xlsx).
No field names or types are hardcoded in this file.
To add a new AP0 field: edit the AP0 xlsx, run generate_all.py.
"""
import json
import sqlite3
from pathlib import Path
from typing import Optional

from src.models import Company, FieldValue, Product, SupplierRecord
from src.field_spec import FieldSpec, load_fields

_CONFIG   = Path(__file__).parent.parent / "config" / "sqlite_schema.json"
DB_PATH   = Path(__file__).parent.parent / "data" / "haystacked.db"
_SCHEMA   = json.loads(_CONFIG.read_text())


JOIN_SQL = """
SELECT
    p.product_id, p.company_id, p.base_model_id, p.product_name, p.agv_type,
    p.product_description, p.reference_count, p.min_project_value_eur,
    p.max_project_value_eur, p.lead_time_weeks, p.distribution_model,
    p.is_oem_product, p.service_coverage, p.active,
    c.company_name, c.country, c.languages_spoken, c.certifications_generic,
    c.employee_count_range, c.hq_city, c.founding_year,
    bme.*
FROM products p
JOIN companies c ON p.company_id = c.company_id
JOIN base_model_extensions bme ON p.base_model_id = bme.base_model_id
WHERE p.active = 1
"""


def _parse_multiselect(val) -> list[str]:
    if val is None or val == "":
        return []
    return [v.strip() for v in str(val).split("|") if v.strip()]


def _parse_bool(val) -> Optional[bool]:
    if val is None:
        return None
    if isinstance(val, int):
        return bool(val)
    s = str(val).lower().strip()
    if s in ("1", "true", "yes"):
        return True
    if s in ("0", "false", "no"):
        return False
    return None


def _parse_int(val) -> Optional[int]:
    if val is None or val == "":
        return None
    try:
        return int(float(val))
    except (ValueError, TypeError):
        return None


def _parse_float(val) -> Optional[float]:
    if val is None or val == "":
        return None
    try:
        v = float(val)
        return None if v != v else v  # reject NaN
    except (ValueError, TypeError):
        return None


def _coerce_by_type(data_type: str, val):
    if data_type == "Boolean":      return _parse_bool(val)
    if data_type == "Integer":      return _parse_int(val)
    if data_type == "Float":        return _parse_float(val)
    if data_type == "Multi-Select": return _parse_multiselect(val)
    return val  # Dropdown / Text passthrough


def _build_field_values(
    row_ext: dict, row_prod: dict, row_company: dict,
    specs: dict[str, FieldSpec]
) -> dict[str, FieldValue]:
    values = {}
    for uuid, spec in specs.items():
        if spec.entity == "Product":
            source = row_prod
        elif spec.entity == "Company":
            source = row_company
        else:  # "Base Model"
            source = row_ext
        raw = source.get(spec.field_name)
        values[uuid] = FieldValue(spec=spec, value=_coerce_by_type(spec.data_type, raw))
    return values


def load_suppliers(db_path: Path = DB_PATH) -> list[SupplierRecord]:
    if not db_path.exists():
        raise FileNotFoundError(
            f"Database not found: {db_path}\n"
            "Run sync_airtable.py first to create it."
        )

    # Startup guard: all entity values in fields.json must be known.
    _KNOWN_ENTITIES = {"Base Model", "Product", "Company"}
    _unknown_entities = {s.entity for s in load_fields().values()} - _KNOWN_ENTITIES
    assert not _unknown_entities, f"Unknown entity values in fields.json: {_unknown_entities}"

    con = sqlite3.connect(db_path)
    con.row_factory = sqlite3.Row
    cur = con.cursor()
    cur.execute(JOIN_SQL)
    rows = cur.fetchall()
    con.close()

    records: list[SupplierRecord] = []
    for row in rows:
        d = dict(row)

        # First-occurrence dict: products/companies columns win over bme.* for overlapping names.
        # sqlite3.Row.keys() returns all columns in SELECT order (including duplicates).
        row_first: dict = {}
        for i, key in enumerate(row.keys()):
            if key not in row_first:
                row_first[key] = row[i]

        product = Product(
            product_id            = row_first["product_id"],
            company_id            = row_first["company_id"],
            base_model_id         = row_first["base_model_id"],
            product_name          = row_first["product_name"],
            agv_type              = row_first["agv_type"],
            product_description   = row_first.get("product_description"),
            reference_count       = _parse_int(row_first.get("reference_count")),
            min_project_value_eur = _parse_int(row_first.get("min_project_value_eur")),
            max_project_value_eur = _parse_int(row_first.get("max_project_value_eur")),
            lead_time_weeks       = _parse_int(row_first.get("lead_time_weeks")),
            distribution_model    = row_first.get("distribution_model"),
            is_oem_product        = _parse_bool(row_first.get("is_oem_product")),
            service_coverage      = _parse_multiselect(row_first.get("service_coverage")),
            active                = _parse_bool(row_first.get("active")),
            company_name          = row_first.get("company_name"),
            country               = row_first.get("country"),
            languages_spoken      = _parse_multiselect(row_first.get("languages_spoken")),
            certifications_generic= _parse_multiselect(row_first.get("certifications_generic")),
        )

        values = _build_field_values(
            row_ext=d, row_prod=row_first, row_company=row_first,
            specs=load_fields(),
        )

        records.append(SupplierRecord(product=product, values=values))

    return records
