"""
AP-I1 — Data Loader
Loads SupplierRecords from SQLite via a 3-way JOIN.
Parsing rules per spec v1.2 LL-06 and Blank != Zero principle.

Extension is schema-driven: field names and types come from config/sqlite_schema.json
(generated by generate_all.py from AP0 xlsx). No field names or types are hardcoded
in this file. To add a new AP0 field: edit the AP0 xlsx, run generate_all.py.
"""
import json
import sqlite3
from pathlib import Path
from typing import Optional

from src.models import Company, Extension, Product, SupplierRecord

_CONFIG   = Path(__file__).parent.parent / "config" / "sqlite_schema.json"
DB_PATH   = Path(__file__).parent.parent / "data" / "haystacked.db"
_SCHEMA   = json.loads(_CONFIG.read_text())

_BOOL_F   = frozenset(_SCHEMA["bool_fields"])
_INT_F    = frozenset(_SCHEMA["int_fields"])
_FLOAT_F  = frozenset(_SCHEMA["float_fields"])
_MS_F     = frozenset(_SCHEMA["multiselect_fields"])
_SHARED   = frozenset(_SCHEMA["shared_in_product_columns"])
_SKIP_EXT = _SHARED | {"extra_fields"}


JOIN_SQL = """
SELECT
    p.product_id, p.company_id, p.base_model_id, p.product_name, p.agv_type,
    p.product_description, p.reference_count, p.min_project_value_eur,
    p.max_project_value_eur, p.lead_time_weeks, p.distribution_model,
    p.is_oem_product, p.service_coverage, p.active,
    c.company_name, c.country, c.languages_spoken, c.certifications_generic,
    c.employee_count_range, c.hq_city, c.founding_year,
    bme.*
FROM products p
JOIN companies c ON p.company_id = c.company_id
JOIN base_model_extensions bme ON p.base_model_id = bme.base_model_id
WHERE p.active = 1
"""


def _parse_multiselect(val) -> list[str]:
    if val is None or val == "":
        return []
    return [v.strip() for v in str(val).split("|") if v.strip()]


def _parse_bool(val) -> Optional[bool]:
    if val is None:
        return None
    if isinstance(val, int):
        return bool(val)
    s = str(val).lower().strip()
    if s in ("1", "true", "yes"):
        return True
    if s in ("0", "false", "no"):
        return False
    return None


def _parse_int(val) -> Optional[int]:
    if val is None or val == "":
        return None
    try:
        return int(float(val))
    except (ValueError, TypeError):
        return None


def _parse_float(val) -> Optional[float]:
    if val is None or val == "":
        return None
    try:
        v = float(val)
        return None if v != v else v  # reject NaN
    except (ValueError, TypeError):
        return None


def _coerce(field_name: str, val):
    """Apply the correct parser for a field based on its AP0 data type."""
    if field_name in _BOOL_F:   return _parse_bool(val)
    if field_name in _INT_F:    return _parse_int(val)
    if field_name in _FLOAT_F:  return _parse_float(val)
    if field_name in _MS_F:     return _parse_multiselect(val)
    return val  # TEXT / Dropdown passthrough


def load_suppliers(db_path: Path = DB_PATH) -> list[SupplierRecord]:
    if not db_path.exists():
        raise FileNotFoundError(
            f"Database not found: {db_path}\n"
            "Run sync_airtable.py first to create it."
        )

    # Startup guard: all AP0 extension fields must be known to Extension or Product.
    # Uses schema["shared_in_product_columns"] — no hardcoded field names here.
    import dataclasses as _dc
    _known = (
        {f.name for f in _dc.fields(Extension)}
        | {f.name for f in _dc.fields(Product)}
        | {"extension_id", "base_model_id", "agv_type", "extra_fields"}
    )
    _missing = set(_SCHEMA["extensions_columns"]) - _known
    assert not _missing, (
        f"AP0 fields missing from Extension/Product dataclass: {sorted(_missing)}\n"
        "Edit the AP0 xlsx and run generate_all.py to regenerate src/generated_models.py."
    )

    con = sqlite3.connect(db_path)
    con.row_factory = sqlite3.Row
    cur = con.cursor()
    cur.execute(JOIN_SQL)
    rows = cur.fetchall()
    con.close()

    records: list[SupplierRecord] = []
    for row in rows:
        d = dict(row)

        product = Product(
            product_id            = d["product_id"],
            company_id            = d["company_id"],
            base_model_id         = d["base_model_id"],
            product_name          = d["product_name"],
            agv_type              = d["agv_type"],
            product_description   = d.get("product_description"),
            reference_count       = _parse_int(d.get("reference_count")),
            min_project_value_eur = _parse_int(d.get("min_project_value_eur")),
            max_project_value_eur = _parse_int(d.get("max_project_value_eur")),
            lead_time_weeks       = _parse_int(d.get("lead_time_weeks")),
            distribution_model    = d.get("distribution_model"),
            is_oem_product        = _parse_bool(d.get("is_oem_product")),
            service_coverage      = _parse_multiselect(d.get("service_coverage")),
            active                = _parse_bool(d.get("active")),
            company_name          = d.get("company_name"),
            country               = d.get("country"),
            languages_spoken      = _parse_multiselect(d.get("languages_spoken")),
            certifications_generic= _parse_multiselect(d.get("certifications_generic")),
        )

        # Schema-driven Extension construction: field names and types from sqlite_schema.json.
        # _SKIP_EXT excludes shared_in_product_columns (loaded into Product above) and extra_fields.
        ext_data = {
            f: _coerce(f, d.get(f))
            for f in _SCHEMA["extensions_columns"]
            if f not in _SKIP_EXT
        }
        ext_data["extra_fields"] = d.get("extra_fields")
        ext = Extension(**ext_data)

        records.append(SupplierRecord(product=product, extension=ext))

    return records
