# src/field_spec.py  — GENERATED by scripts/generate_all.py — do not edit manually
from __future__ import annotations
from dataclasses import dataclass
from typing import Optional
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
_FIELDS_JSON = ROOT / "config" / "fields.json"


@dataclass
class FieldSpec:
    uuid: str
    field_name: str
    tender_key: Optional[str]
    entity: str
    scope: str
    level: Optional[str]
    operator: Optional[str]
    data_type: str
    unit: Optional[str]
    allowed_values: Optional[list]
    score_function: Optional[str]
    threshold_a: Optional[float]
    threshold_b: Optional[float]
    scoring_weight: Optional[int]
    hint: Optional[str]
    user_description: Optional[str]
    display_mode: Optional[str]
    value_if_null: object = None


def load_fields() -> dict[str, FieldSpec]:
    """Returns all fields keyed by UUID. Asserts UUID uniqueness."""
    data = json.loads(_FIELDS_JSON.read_text())
    result = {k: FieldSpec(**v) for k, v in data.items()}
    assert len(result) == len(data), "Duplicate UUIDs in fields.json"
    return result


def fields_by_tender_key() -> dict[str, list[FieldSpec]]:
    """Returns fields grouped by tender_key. One key can map to multiple VT-scoped fields.
    Only includes fields where tender_key is not None."""
    result: dict[str, list[FieldSpec]] = {}
    for f in load_fields().values():
        if f.tender_key:
            result.setdefault(f.tender_key, []).append(f)
    return result


def fields_by_field_name() -> dict[str, list[FieldSpec]]:
    """Returns fields grouped by field_name. One name can appear in multiple VT scopes."""
    result: dict[str, list[FieldSpec]] = {}
    for f in load_fields().values():
        result.setdefault(f.field_name, []).append(f)
    return result


